### PR TITLE
Create zhufengnodejs

### PR DESCRIPTION
**Pull request by zhufengnodejs**
我觉得我写的好,快来拉去我的代码吧

### CODE REVIEW

**Comment by ananten** [comment]
哈哈哈哈

**Comment by zhufengnodejs** [comment]
我觉得写得不好

**Comment by lyly22** [comment]
写的不错

**Comment by yangxw2015** [comment]
我写的也很好

**Comment by wei123123xue** [comment]
O(∩_∩)O哈哈哈~

**Comment by yuyuxuanxiaogit** [comment]
哈哈哈

**Comment by ananten** [comment]
:100:

**Comment by panpanYU** [comment]
老师刚刚的笑声好逗

**Comment by lankaixuan** [comment]
写的不错

**Comment by zhufengnodejs** [comment]
:+1: 
:santa: 
:sandal:

**Comment by yangxw2015** [comment]
:+1:

**Comment by luohuanhuan** [comment]
:100:

**Comment by wudanjs** [comment]
:100:

**Comment by woshilijing** [comment]
good

**Comment by aifang90** [comment]
can not see clearly

**Comment by gongjurui** [comment]
1c3ff37911ea74a5585a4605cf1d2620

**Comment by ananten** [comment]
c5fc3c1a6654cb95ac6e75a1_cr

**Comment by aifang90** [comment]
can not see clearly
u 2421926602 3094332691 fm 21 gp 0

**Comment by eric1999** [comment]
你愁啥

**Comment by yi920123** [comment]
image

**Comment by z649319834** [comment]
2454567890

**Comment by yanmeiyuan11** [comment]
??

**Pull request merged**
